[workspace]

[lib]
crate_type = ["staticlib"]

[package]
name = "afx_hook_source2_rs"
version = "0.1.0"
authors = ["advancedfx.org <contact@advancedfx.org>"]
license = "MIT"
homepage = "https://github.com/advancedfx"
repository = "https://github.com/advancedfx/advancedfx"
edition = "2021"

[dependencies]
boa_engine = { git = "https://github.com/boa-dev/boa.git", rev = "fd1a34860127e165babafd29f978acaddb0036f0" }
boa_gc = { git = "https://github.com/boa-dev/boa.git", rev = "fd1a34860127e165babafd29f978acaddb0036f0" }
async-tungstenite = { version = "0.25.0", features = ["async-std-runtime"] }
futures = "0.3.30"
pollster = "0.3.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
# debug = true