#include "stdafx.h"

#include "MirvImage.h"

#include "AfxShaders.h"
#include "Globals.h"
#include "hlaeFolder.h"

#include "../shared/StringTools.h"
#include "../deps/release/prop/AfxHookSource/SourceSdkShared.h"

#include "../shaders/build/afx_drawtexture_vs_5_0.h" // autogenerated
#include "../shaders/build/afx_drawtexture_ps_5_0.h" // autogenerated

#include <objbase.h>
#include <wincodec.h>

#include <algorithm>
#include <vector>

extern SOURCESDK::VMatrix g_WorldToScreenMatrix;

CMirvImageDrawer g_MirvImageDrawer;

using Afx::Math::Vector3;

namespace {

class CComInitScope {
public:
	CComInitScope() {
		m_Hr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
	}

	~CComInitScope() {
		if (SUCCEEDED(m_Hr)) {
			CoUninitialize();
		}
	}

	bool IsOk() const {
		return SUCCEEDED(m_Hr) || m_Hr == RPC_E_CHANGED_MODE;
	}

private:
	HRESULT m_Hr = E_FAIL;
};

void SafeRelease(IUnknown* ptr) {
	if (ptr) ptr->Release();
}

std::wstring BuildImagePath(const std::wstring& fileName) {
	std::wstring path = GetHlaeFolderW();
	path += L"resources\\AfxHookSource2\\images\\";
	path += fileName;
	return path;
}

} // namespace

CMirvImageDrawer::CMirvImageDrawer() = default;

CMirvImageDrawer::~CMirvImageDrawer() {
	EndDevice();
}

void CMirvImageDrawer::BeginDevice(ID3D11Device* device) {
	EndDevice();

	if (!device) return;

	device->AddRef();
	m_Device = device;
	m_Device->CreateDeferredContext(0, &m_DeviceContext);
}

void CMirvImageDrawer::EndDevice() {
	if (!m_Device) return;

	if (m_VertexBuffer) { m_VertexBuffer->Release(); m_VertexBuffer = nullptr; }
	if (m_PixelShader) { m_PixelShader->Release(); m_PixelShader = nullptr; }
	if (m_VertexShader) { m_VertexShader->Release(); m_VertexShader = nullptr; }
	if (m_ConstantBuffer) { m_ConstantBuffer->Release(); m_ConstantBuffer = nullptr; }
	if (m_InputLayout) { m_InputLayout->Release(); m_InputLayout = nullptr; }
	if (m_BlendState) { m_BlendState->Release(); m_BlendState = nullptr; }
	if (m_RasterizerState) { m_RasterizerState->Release(); m_RasterizerState = nullptr; }
	if (m_SamplerState) { m_SamplerState->Release(); m_SamplerState = nullptr; }
	if (m_DepthStateOff) { m_DepthStateOff->Release(); m_DepthStateOff = nullptr; }
	if (m_DepthStateOn) { m_DepthStateOn->Release(); m_DepthStateOn = nullptr; }

	if (m_DeviceContext) { m_DeviceContext->Release(); m_DeviceContext = nullptr; }

	{
		std::lock_guard<std::mutex> lock(m_Mutex);
		for (auto& entry : m_Images) {
			ReleaseImageResources(entry);
			entry.pendingLoad = true;
		}
	}

	m_Device->Release();
	m_Device = nullptr;
}

void CMirvImageDrawer::OnRenderThread_Draw(
	ID3D11DeviceContext* pImmediateContext,
	const D3D11_VIEWPORT* pViewPort,
	ID3D11RenderTargetView* pRenderTargetView,
	ID3D11DepthStencilView* pDepthStencilView
) {
	if (!m_Device || !m_DeviceContext || !pImmediateContext || !pViewPort || !pRenderTargetView) return;

	m_ImmediateContext = pImmediateContext;
	m_pViewPort = pViewPort;
	m_Rtv = pRenderTargetView;
	m_Dsv = pDepthStencilView;

	EnsureDeviceResources();
	DrawImages();

	m_Dsv = nullptr;
	m_Rtv = nullptr;
	m_pViewPort = nullptr;
	m_ImmediateContext = nullptr;
}

void CMirvImageDrawer::LoadImage(const char* name, const char* fileName) {
	if (!name || !fileName) return;

	std::wstring wFileName;
	if (!UTF8StringToWideString(fileName, wFileName)) {
		advancedfx::Warning("mirv_image: failed to convert file name to wide string.\n");
		return;
	}

	std::wstring fullPath = BuildImagePath(wFileName);

	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) {
		ImageEntry newEntry;
		newEntry.name = name;
		newEntry.filePath = fullPath;
		newEntry.visible = true;
		newEntry.pendingLoad = true;
		m_Images.push_back(std::move(newEntry));
	} else {
		entry->filePath = fullPath;
		entry->visible = true;
		entry->pendingLoad = true;
		ReleaseImageResources(*entry);
	}
}

void CMirvImageDrawer::UnloadImage(const char* name) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	auto it = std::find_if(m_Images.begin(), m_Images.end(),
		[name](const ImageEntry& entry) { return entry.name == name; });
	if (it == m_Images.end()) return;
	ReleaseImageResources(*it);
	m_Images.erase(it);
}

void CMirvImageDrawer::ListImages() {
	std::lock_guard<std::mutex> lock(m_Mutex);
	advancedfx::Message("mirv_image: %zu image(s)\n", m_Images.size());
	for (const auto& entry : m_Images) {
		advancedfx::Message(
			"  %s pos(%.2f %.2f %.2f) ang(%.2f %.2f %.2f) scale(%.2f %.2f) visible=%d depth=%d\n",
			entry.name.c_str(),
			entry.position.X, entry.position.Y, entry.position.Z,
			entry.pitch, entry.yaw, entry.roll,
			entry.scaleX, entry.scaleY,
			entry.visible ? 1 : 0,
			entry.depthTest ? 1 : 0
		);
	}
}

void CMirvImageDrawer::SetPosition(const char* name, double x, double y, double z) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->position = Vector3(x, y, z);
}

void CMirvImageDrawer::SetAngles(const char* name, double pitch, double yaw, double roll) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->pitch = pitch;
	entry->yaw = yaw;
	entry->roll = roll;
}

void CMirvImageDrawer::SetScale(const char* name, double sx, double sy) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->scaleX = sx;
	entry->scaleY = sy;
}

void CMirvImageDrawer::SetVisible(const char* name, bool value) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->visible = value;
}

void CMirvImageDrawer::SetDepthTest(const char* name, bool value) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->depthTest = value;
}

CMirvImageDrawer::ImageEntry* CMirvImageDrawer::FindImageLocked(const std::string& name) {
	auto it = std::find_if(m_Images.begin(), m_Images.end(),
		[&name](const ImageEntry& entry) { return entry.name == name; });
	if (it == m_Images.end()) return nullptr;
	return &(*it);
}

void CMirvImageDrawer::ReleaseImageResources(ImageEntry& entry) {
	if (entry.srv) { entry.srv->Release(); entry.srv = nullptr; }
	if (entry.texture) { entry.texture->Release(); entry.texture = nullptr; }
	entry.width = 0;
	entry.height = 0;
}

bool CMirvImageDrawer::LoadTextureFromFile(
	const std::wstring& filePath,
	ID3D11Texture2D** outTexture,
	ID3D11ShaderResourceView** outSrv,
	UINT* outWidth,
	UINT* outHeight
) {
	if (!m_Device) return false;
	if (!outTexture || !outSrv) return false;

	*outTexture = nullptr;
	*outSrv = nullptr;
	if (outWidth) *outWidth = 0;
	if (outHeight) *outHeight = 0;

	CComInitScope comInit;
	if (!comInit.IsOk()) {
		advancedfx::Warning("mirv_image: COM initialization failed.\n");
		return false;
	}

	HRESULT hr = E_FAIL;
	IWICImagingFactory* factory = nullptr;
	IWICBitmapDecoder* decoder = nullptr;
	IWICBitmapFrameDecode* frame = nullptr;
	IWICFormatConverter* converter = nullptr;
	ID3D11Texture2D* texture = nullptr;
	ID3D11ShaderResourceView* srv = nullptr;
	UINT width = 0;
	UINT height = 0;
	std::vector<unsigned char> pixels;

	do {
		hr = CoCreateInstance(
			CLSID_WICImagingFactory,
			nullptr,
			CLSCTX_INPROC_SERVER,
			IID_PPV_ARGS(&factory)
		);
		if (FAILED(hr)) break;

		hr = factory->CreateDecoderFromFilename(
			filePath.c_str(),
			nullptr,
			GENERIC_READ,
			WICDecodeMetadataCacheOnLoad,
			&decoder
		);
		if (FAILED(hr)) break;

		hr = decoder->GetFrame(0, &frame);
		if (FAILED(hr)) break;

		hr = factory->CreateFormatConverter(&converter);
		if (FAILED(hr)) break;

		hr = converter->Initialize(
			frame,
			GUID_WICPixelFormat32bppBGRA,
			WICBitmapDitherTypeNone,
			nullptr,
			0.0,
			WICBitmapPaletteTypeCustom
		);
		if (FAILED(hr)) break;

		hr = converter->GetSize(&width, &height);
		if (FAILED(hr) || 0 == width || 0 == height) break;

		pixels.resize(width * height * 4);
		hr = converter->CopyPixels(nullptr, width * 4, static_cast<UINT>(pixels.size()), pixels.data());
		if (FAILED(hr)) break;

		D3D11_SUBRESOURCE_DATA subResource = {};
		subResource.pSysMem = pixels.data();
		subResource.SysMemPitch = width * 4;

		D3D11_TEXTURE2D_DESC textureDesc = {};
		textureDesc.Width = width;
		textureDesc.Height = height;
		textureDesc.MipLevels = 1;
		textureDesc.ArraySize = 1;
		textureDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
		textureDesc.SampleDesc.Count = 1;
		textureDesc.Usage = D3D11_USAGE_IMMUTABLE;
		textureDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;

		hr = m_Device->CreateTexture2D(&textureDesc, &subResource, &texture);
		if (FAILED(hr)) break;

		D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
		srvDesc.Format = textureDesc.Format;
		srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
		srvDesc.Texture2D.MostDetailedMip = 0;
		srvDesc.Texture2D.MipLevels = 1;

		hr = m_Device->CreateShaderResourceView(texture, &srvDesc, &srv);
		if (FAILED(hr)) break;

		*outTexture = texture;
		*outSrv = srv;
		if (outWidth) *outWidth = width;
		if (outHeight) *outHeight = height;
	} while (false);

	if (FAILED(hr)) {
		if (srv) { srv->Release(); srv = nullptr; }
		if (texture) { texture->Release(); texture = nullptr; }
	}

	SafeRelease(converter);
	SafeRelease(frame);
	SafeRelease(decoder);
	SafeRelease(factory);

	return SUCCEEDED(hr);
}

void CMirvImageDrawer::EnsureDeviceResources() {
	if (!m_Device || !m_DeviceContext) return;
	if (m_VertexShader && m_PixelShader && m_InputLayout && m_ConstantBuffer && m_VertexBuffer
		&& m_BlendState && m_RasterizerState && m_SamplerState && m_DepthStateOn && m_DepthStateOff) {
		return;
	}

	size_t size = 0;
	void* so = LoadFromAcsShaderFileInMemory(L"afx_drawtexture_vs_5_0.acs", ShaderCombo_afx_drawtexture_vs_5_0::GetCombo(), size);
	if (so) {
		m_Device->CreateVertexShader(so, size, NULL, &m_VertexShader);

		D3D11_INPUT_ELEMENT_DESC inputDesc[5] = {
			{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"COLOR", 0, DXGI_FORMAT_B8G8R8A8_UNORM, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD", 1, DXGI_FORMAT_R32G32B32_FLOAT, 0, 28, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD", 2, DXGI_FORMAT_R32G32B32_FLOAT, 0, 40, D3D11_INPUT_PER_VERTEX_DATA, 0},
		};
		m_Device->CreateInputLayout(inputDesc, 5, so, size, &m_InputLayout);
		free(so);
	}

	so = LoadFromAcsShaderFileInMemory(L"afx_drawtexture_ps_5_0.acs", ShaderCombo_afx_drawtexture_ps_5_0::GetCombo(), size);
	if (so) {
		m_Device->CreatePixelShader(so, size, NULL, &m_PixelShader);
		free(so);
	}

	{
		D3D11_BUFFER_DESC cbDesc = {};
		cbDesc.ByteWidth = sizeof(VS_CONSTANT_BUFFER);
		cbDesc.Usage = D3D11_USAGE_DYNAMIC;
		cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
		cbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
		m_Device->CreateBuffer(&cbDesc, nullptr, &m_ConstantBuffer);
	}

	{
		D3D11_BUFFER_DESC vbDesc = {};
		vbDesc.ByteWidth = sizeof(Vertex) * 4;
		vbDesc.Usage = D3D11_USAGE_DYNAMIC;
		vbDesc.BindFlags = D3D11_BIND_VERTEX_BUFFER;
		vbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
		m_Device->CreateBuffer(&vbDesc, nullptr, &m_VertexBuffer);
	}

	{
		D3D11_DEPTH_STENCIL_DESC depthDesc = {};
		depthDesc.DepthEnable = TRUE;
		depthDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
		depthDesc.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
		m_Device->CreateDepthStencilState(&depthDesc, &m_DepthStateOn);
	}
	{
		D3D11_DEPTH_STENCIL_DESC depthDesc = {};
		depthDesc.DepthEnable = FALSE;
		depthDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
		depthDesc.DepthFunc = D3D11_COMPARISON_ALWAYS;
		m_Device->CreateDepthStencilState(&depthDesc, &m_DepthStateOff);
	}
	{
		D3D11_SAMPLER_DESC samplerDesc = {};
		samplerDesc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
		samplerDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.ComparisonFunc = D3D11_COMPARISON_ALWAYS;
		samplerDesc.MinLOD = -D3D11_FLOAT32_MAX;
		samplerDesc.MaxLOD = D3D11_FLOAT32_MAX;
		m_Device->CreateSamplerState(&samplerDesc, &m_SamplerState);
	}
	{
		D3D11_RASTERIZER_DESC rasterizerDesc = {};
		rasterizerDesc.FillMode = D3D11_FILL_SOLID;
		rasterizerDesc.CullMode = D3D11_CULL_NONE;
		rasterizerDesc.FrontCounterClockwise = TRUE;
		rasterizerDesc.DepthClipEnable = TRUE;
		rasterizerDesc.MultisampleEnable = TRUE;
		m_Device->CreateRasterizerState(&rasterizerDesc, &m_RasterizerState);
	}
	{
		D3D11_BLEND_DESC blendDesc = {};
		blendDesc.AlphaToCoverageEnable = FALSE;
		blendDesc.IndependentBlendEnable = FALSE;
		auto& rtDesc = blendDesc.RenderTarget[0];
		rtDesc.BlendEnable = TRUE;
		rtDesc.SrcBlend = D3D11_BLEND_SRC_ALPHA;
		rtDesc.DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
		rtDesc.BlendOp = D3D11_BLEND_OP_ADD;
		rtDesc.SrcBlendAlpha = D3D11_BLEND_SRC_ALPHA;
		rtDesc.DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
		rtDesc.BlendOpAlpha = D3D11_BLEND_OP_ADD;
		rtDesc.RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
		m_Device->CreateBlendState(&blendDesc, &m_BlendState);
	}
}

bool CMirvImageDrawer::SetMatrixConstantBuffer() {
	if (!m_DeviceContext || !m_ConstantBuffer) return false;

	VS_CONSTANT_BUFFER constants = {};
	constants.matrix = DirectX::XMFLOAT4X4(
		(float)g_WorldToScreenMatrix.m[0][0], (float)g_WorldToScreenMatrix.m[0][1], (float)g_WorldToScreenMatrix.m[0][2], (float)g_WorldToScreenMatrix.m[0][3],
		(float)g_WorldToScreenMatrix.m[1][0], (float)g_WorldToScreenMatrix.m[1][1], (float)g_WorldToScreenMatrix.m[1][2], (float)g_WorldToScreenMatrix.m[1][3],
		(float)g_WorldToScreenMatrix.m[2][0], (float)g_WorldToScreenMatrix.m[2][1], (float)g_WorldToScreenMatrix.m[2][2], (float)g_WorldToScreenMatrix.m[2][3],
		(float)g_WorldToScreenMatrix.m[3][0], (float)g_WorldToScreenMatrix.m[3][1], (float)g_WorldToScreenMatrix.m[3][2], (float)g_WorldToScreenMatrix.m[3][3]
	);

	D3D11_MAPPED_SUBRESOURCE mapped = {};
	if (FAILED(m_DeviceContext->Map(m_ConstantBuffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) return false;
	memcpy(mapped.pData, &constants, sizeof(constants));
	m_DeviceContext->Unmap(m_ConstantBuffer, 0);
	return true;
}

void CMirvImageDrawer::DrawImages() {
	if (!(m_Device && m_DeviceContext && m_VertexShader && m_PixelShader && m_InputLayout && m_ConstantBuffer
		&& m_VertexBuffer && m_BlendState && m_RasterizerState && m_SamplerState && m_DepthStateOn
		&& m_DepthStateOff && m_ImmediateContext && m_Rtv && m_pViewPort)) {
		return;
	}

	m_DeviceContext->OMSetRenderTargets(1, &m_Rtv, m_Dsv);
	m_DeviceContext->RSSetViewports(1, m_pViewPort);

	if (!SetMatrixConstantBuffer()) return;
	m_DeviceContext->VSSetConstantBuffers(0, 1, &m_ConstantBuffer);

	UINT stride = sizeof(Vertex);
	UINT offset = 0;
	m_DeviceContext->IASetVertexBuffers(0, 1, &m_VertexBuffer, &stride, &offset);
	m_DeviceContext->IASetInputLayout(m_InputLayout);
	m_DeviceContext->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);

	m_DeviceContext->VSSetShader(m_VertexShader, nullptr, 0);
	m_DeviceContext->PSSetShader(m_PixelShader, nullptr, 0);
	m_DeviceContext->PSSetSamplers(0, 1, &m_SamplerState);
	m_DeviceContext->RSSetState(m_RasterizerState);
	m_DeviceContext->OMSetBlendState(m_BlendState, nullptr, 0xffffffff);

	std::lock_guard<std::mutex> lock(m_Mutex);
	for (auto& entry : m_Images) {
		if (entry.pendingLoad && !entry.filePath.empty()) {
			ReleaseImageResources(entry);
			entry.pendingLoad = false;
			if (!LoadTextureFromFile(entry.filePath, &entry.texture, &entry.srv, &entry.width, &entry.height)) {
				advancedfx::Warning("mirv_image: failed to load image.\n");
			}
		}
		if (!entry.visible || !entry.srv) continue;

		double forward[3] = {};
		double right[3] = {};
		double up[3] = {};
		Afx::Math::MakeVectors(entry.roll, entry.pitch, entry.yaw, forward, right, up);

		Vector3 vRight(right[0], right[1], right[2]);
		Vector3 vUp(up[0], up[1], up[2]);

		double halfX = entry.scaleX * 0.5;
		double halfY = entry.scaleY * 0.5;

		Vector3 p0 = entry.position - vRight * halfX + vUp * halfY;
		Vector3 p1 = entry.position - vRight * halfX - vUp * halfY;
		Vector3 p2 = entry.position + vRight * halfX + vUp * halfY;
		Vector3 p3 = entry.position + vRight * halfX - vUp * halfY;

		D3D11_MAPPED_SUBRESOURCE mapped = {};
		if (FAILED(m_DeviceContext->Map(m_VertexBuffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) continue;
		Vertex* v = reinterpret_cast<Vertex*>(mapped.pData);

		const DWORD white = 0xFFFFFFFF;
		v[0] = { (float)p0.X, (float)p0.Y, (float)p0.Z, white, 0.0f, 0.0f, 0.0f, 0, 0, 0, 0, 0, 0 };
		v[1] = { (float)p1.X, (float)p1.Y, (float)p1.Z, white, 0.0f, 1.0f, 0.0f, 0, 0, 0, 0, 0, 0 };
		v[2] = { (float)p2.X, (float)p2.Y, (float)p2.Z, white, 1.0f, 0.0f, 0.0f, 0, 0, 0, 0, 0, 0 };
		v[3] = { (float)p3.X, (float)p3.Y, (float)p3.Z, white, 1.0f, 1.0f, 0.0f, 0, 0, 0, 0, 0, 0 };

		m_DeviceContext->Unmap(m_VertexBuffer, 0);

		ID3D11DepthStencilState* depthState = entry.depthTest ? m_DepthStateOn : m_DepthStateOff;
		m_DeviceContext->OMSetDepthStencilState(depthState, 0);
		m_DeviceContext->PSSetShaderResources(0, 1, &entry.srv);
		m_DeviceContext->Draw(4, 0);
	}

	ID3D11CommandList* commandList = nullptr;
	m_DeviceContext->FinishCommandList(FALSE, &commandList);
	if (commandList) {
		m_ImmediateContext->ExecuteCommandList(commandList, TRUE);
		commandList->Release();
	}
}

CON_COMMAND(mirv_image, "3D image drawing in world space.")
{
	int argc = args->ArgC();
	const char* cmd0 = args->ArgV(0);

	if (2 <= argc) {
		const char* cmd1 = args->ArgV(1);
		if (0 == _stricmp(cmd1, "load")) {
			if (4 <= argc) {
				g_MirvImageDrawer.LoadImage(args->ArgV(2), args->ArgV(3));
				return;
			}
		} else if (0 == _stricmp(cmd1, "unload")) {
			if (3 <= argc) {
				g_MirvImageDrawer.UnloadImage(args->ArgV(2));
				return;
			}
		} else if (0 == _stricmp(cmd1, "list")) {
			g_MirvImageDrawer.ListImages();
			return;
		} else if (0 == _stricmp(cmd1, "place")) {
			if (6 <= argc) {
				g_MirvImageDrawer.SetPosition(args->ArgV(2), atof(args->ArgV(3)), atof(args->ArgV(4)), atof(args->ArgV(5)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "angles")) {
			if (6 <= argc) {
				g_MirvImageDrawer.SetAngles(args->ArgV(2), atof(args->ArgV(3)), atof(args->ArgV(4)), atof(args->ArgV(5)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "scale")) {
			if (5 <= argc) {
				g_MirvImageDrawer.SetScale(args->ArgV(2), atof(args->ArgV(3)), atof(args->ArgV(4)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "show")) {
			if (4 <= argc) {
				g_MirvImageDrawer.SetVisible(args->ArgV(2), 0 != atoi(args->ArgV(3)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "depth")) {
			if (4 <= argc) {
				g_MirvImageDrawer.SetDepthTest(args->ArgV(2), 0 != atoi(args->ArgV(3)));
				return;
			}
		}
	}

	advancedfx::Message(
		"%s load <name> <file> - Load PNG from resources\\\\AfxHookSource2\\\\images.\n"
		"%s unload <name> - Unload image.\n"
		"%s list - List images.\n"
		"%s place <name> <x> <y> <z> - Set world position.\n"
		"%s angles <name> <pitch> <yaw> <roll> - Set world angles.\n"
		"%s scale <name> <sx> <sy> - Set world size.\n"
		"%s show <name> 0|1 - Show or hide image.\n"
		"%s depth <name> 0|1 - Disable or enable depth testing.\n",
		cmd0, cmd0, cmd0, cmd0, cmd0, cmd0, cmd0, cmd0
	);
}
