#include "stdafx.h"

#include "MirvImage.h"

#include "AfxShaders.h"
#include "Globals.h"
#include "hlaeFolder.h"
#include "ClientEntitySystem.h"
#include "ObsSpectatorBindings.h"
#include "RenderSystemDX11Hooks.h"

#include "../shared/StringTools.h"
#include "../deps/release/prop/AfxHookSource/SourceSdkShared.h"

#include "../shaders/build/afx_drawtexture_vs_5_0.h" // autogenerated
#include "../shaders/build/afx_drawtexture_ps_5_0.h" // autogenerated

#include <dxgi.h>
#include <objbase.h>
#include <wincodec.h>

#include <algorithm>
#include <cstdlib>
#include <vector>

extern SOURCESDK::VMatrix g_WorldToScreenMatrix;

CMirvImageDrawer g_MirvImageDrawer;

using Afx::Math::Vector3;

namespace {

class CComInitScope {
public:
	CComInitScope() {
		m_Hr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
	}

	~CComInitScope() {
		if (SUCCEEDED(m_Hr)) {
			CoUninitialize();
		}
	}

	bool IsOk() const {
		return SUCCEEDED(m_Hr) || m_Hr == RPC_E_CHANGED_MODE;
	}

private:
	HRESULT m_Hr = E_FAIL;
};

void SafeRelease(IUnknown* ptr) {
	if (ptr) ptr->Release();
}

std::wstring BuildImagePath(const std::wstring& fileName) {
	std::wstring path = GetHlaeFolderW();
	path += L"resources\\AfxHookSource2\\images\\";
	path += fileName;
	return path;
}

	bool TryGetAttachedTransform(int slot, const std::string& attachmentName, float outOrigin[3], float outAngles[3]) {
		if (slot < 0 || slot > 9) return false;
		if (!g_pEntityList || !*g_pEntityList || !g_GetEntityFromIndex) return false;
		if (g_SpectatorBindings[slot] == -1) return false;

	int controllerIndex = g_SpectatorBindings[slot];
	auto controller = (CEntityInstance*)g_GetEntityFromIndex(*g_pEntityList, controllerIndex);
	if (!controller || !controller->IsPlayerController()) return false;

	auto pawnHandle = controller->GetPlayerPawnHandle();
	if (!pawnHandle.IsValid()) return false;
	int pawnIndex = pawnHandle.GetEntryIndex();
	if (pawnIndex < 0) return false;

	auto pawn = (CEntityInstance*)g_GetEntityFromIndex(*g_pEntityList, pawnIndex);
	if (!pawn || !pawn->IsPlayerPawn() || !pawn->GetHealth() > 0) return false;

	if (attachmentName.empty()) {
		pawn->GetOrigin(outOrigin[0], outOrigin[1], outOrigin[2]);
		pawn->GetRenderEyeAngles(outAngles);
		return true;
	}

	if (attachmentName == "POV") {
		pawn->GetRenderEyeOrigin(outOrigin);
		pawn->GetRenderEyeAngles(outAngles);
		return true;
	}

	uint8_t attachmentIdx = pawn->LookupAttachment(attachmentName.c_str());
	SOURCESDK::Vector attachmentOrigin;
	SOURCESDK::Quaternion attachmentAngles;
	if (!pawn->GetAttachment(attachmentIdx, attachmentOrigin, attachmentAngles)) return false;

	outOrigin[0] = attachmentOrigin.x;
	outOrigin[1] = attachmentOrigin.y;
	outOrigin[2] = attachmentOrigin.z;

	Afx::Math::Quaternion quat(attachmentAngles.w, attachmentAngles.x, attachmentAngles.y, attachmentAngles.z);
	Afx::Math::QEulerAngles euler = quat.ToQREulerAngles().ToQEulerAngles();
	outAngles[0] = (float)euler.Pitch;
	outAngles[1] = (float)euler.Yaw;
	outAngles[2] = (float)euler.Roll;
	return true;
}

} // namespace

CMirvImageDrawer::CMirvImageDrawer() = default;

CMirvImageDrawer::~CMirvImageDrawer() {
	EndDevice();
}

void CMirvImageDrawer::BeginDevice(ID3D11Device* device) {
	EndDevice();

	if (!device) return;

	device->AddRef();
	m_Device = device;
	m_Device->CreateDeferredContext(0, &m_DeviceContext);
}

void CMirvImageDrawer::EndDevice() {
	if (!m_Device) return;

	if (m_VertexBuffer) { m_VertexBuffer->Release(); m_VertexBuffer = nullptr; }
	if (m_PixelShader) { m_PixelShader->Release(); m_PixelShader = nullptr; }
	if (m_VertexShader) { m_VertexShader->Release(); m_VertexShader = nullptr; }
	if (m_ConstantBuffer) { m_ConstantBuffer->Release(); m_ConstantBuffer = nullptr; }
	if (m_InputLayout) { m_InputLayout->Release(); m_InputLayout = nullptr; }
	if (m_BlendState) { m_BlendState->Release(); m_BlendState = nullptr; }
	if (m_BlendStatePremul) { m_BlendStatePremul->Release(); m_BlendStatePremul = nullptr; }
	if (m_RasterizerState) { m_RasterizerState->Release(); m_RasterizerState = nullptr; }
	if (m_SamplerState) { m_SamplerState->Release(); m_SamplerState = nullptr; }
	if (m_DepthStateOff) { m_DepthStateOff->Release(); m_DepthStateOff = nullptr; }
	if (m_DepthStateWrite) { m_DepthStateWrite->Release(); m_DepthStateWrite = nullptr; }
	if (m_DepthStateOn) { m_DepthStateOn->Release(); m_DepthStateOn = nullptr; }

	if (m_DeviceContext) { m_DeviceContext->Release(); m_DeviceContext = nullptr; }

	{
		std::lock_guard<std::mutex> lock(m_Mutex);
		for (auto& entry : m_Images) {
			ReleaseImageResources(entry);
			entry.pendingLoad = true;
		}
		for (auto& atlas : m_Atlases) {
			ReleaseAtlasResources(atlas);
		}
	}

	m_Device->Release();
	m_Device = nullptr;
}

void CMirvImageDrawer::OnRenderThread_Draw(
	ID3D11DeviceContext* pImmediateContext,
	const D3D11_VIEWPORT* pViewPort,
	ID3D11RenderTargetView* pRenderTargetView,
	ID3D11DepthStencilView* pDepthStencilView
) {
	if (!m_Device || !m_DeviceContext || !pImmediateContext || !pViewPort || !pRenderTargetView) return;

	m_ImmediateContext = pImmediateContext;
	m_pViewPort = pViewPort;
	m_Rtv = pRenderTargetView;
	m_Dsv = pDepthStencilView;

	EnsureDeviceResources();
	DrawImages();

	m_Dsv = nullptr;
	m_Rtv = nullptr;
	m_pViewPort = nullptr;
	m_ImmediateContext = nullptr;
}

void CMirvImageDrawer::LoadImage(const char* name, const char* fileName) {
	if (!name || !fileName) return;

	std::wstring wFileName;
	if (!UTF8StringToWideString(fileName, wFileName)) {
		advancedfx::Warning("mirv_image: failed to convert file name to wide string.\n");
		return;
	}

	std::wstring fullPath = BuildImagePath(wFileName);

	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) {
		ImageEntry newEntry;
		newEntry.name = name;
		newEntry.filePath = fullPath;
		newEntry.visible = true;
		newEntry.pendingLoad = true;
		newEntry.useAtlas = false;
		m_Images.push_back(std::move(newEntry));
	} else {
		entry->filePath = fullPath;
		entry->visible = true;
		entry->pendingLoad = true;
		ReleaseImageResources(*entry);
		entry->useAtlas = false;
	}
}

void CMirvImageDrawer::UnloadImage(const char* name) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	auto it = std::find_if(m_Images.begin(), m_Images.end(),
		[name](const ImageEntry& entry) { return entry.name == name; });
	if (it == m_Images.end()) return;
	ReleaseImageResources(*it);
	m_Images.erase(it);
}

void CMirvImageDrawer::Clear() {
	std::lock_guard<std::mutex> lock(m_Mutex);

	for (auto& entry : m_Images) {
		ReleaseImageResources(entry);
	}
	m_Images.clear();

	for (auto& atlas : m_Atlases) {
		ReleaseAtlasResources(atlas);
	}
	m_Atlases.clear();

	m_ProbePending = false;
	m_ProbeAtlasName.clear();
	m_ProbeX = 0;
	m_ProbeY = 0;
}

void CMirvImageDrawer::ListImages() {
	std::lock_guard<std::mutex> lock(m_Mutex);
	advancedfx::Message("mirv_image: %zu image(s)\n", m_Images.size());
	for (const auto& entry : m_Images) {
		const char* attachInfo = "";
		if (entry.attachSlot >= 0) {
			static char attachBuffer[192];
			_snprintf_s(
				attachBuffer,
				sizeof(attachBuffer),
				" attach=slot%d yaw=%d pitch=%d roll=%d%s%s",
				entry.attachSlot,
				entry.attachUseYaw ? 1 : 0,
				entry.attachUsePitch ? 1 : 0,
				entry.attachUseRoll ? 1 : 0,
				entry.attachAttachmentName.empty() ? "" : " attachment=",
				entry.attachAttachmentName.empty() ? "" : entry.attachAttachmentName.c_str()
			);
			attachInfo = attachBuffer;
		}
		advancedfx::Message(
			"  %s pos(%.2f %.2f %.2f) ang(%.2f %.2f %.2f) scale(%.2f %.2f) visible=%d depth=%d depthWrite=%d%s%s\n",
			entry.name.c_str(),
			entry.position.X, entry.position.Y, entry.position.Z,
			entry.pitch, entry.yaw, entry.roll,
			entry.scaleX, entry.scaleY,
			entry.visible ? 1 : 0,
			entry.depthTest ? 1 : 0,
			entry.depthWrite ? 1 : 0,
			entry.useAtlas ? " atlas" : "",
			attachInfo
		);
	}
}

void CMirvImageDrawer::SetPosition(const char* name, double x, double y, double z) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->position = Vector3(x, y, z);
}

void CMirvImageDrawer::SetAngles(const char* name, double pitch, double yaw, double roll) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->pitch = pitch;
	entry->yaw = yaw;
	entry->roll = roll;
}

void CMirvImageDrawer::SetScale(const char* name, double sx, double sy) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->scaleX = sx;
	entry->scaleY = sy;
}

void CMirvImageDrawer::SetVisible(const char* name, bool value) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->visible = value;
}

void CMirvImageDrawer::SetDepthTest(const char* name, bool value) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->depthTest = value;
}

void CMirvImageDrawer::SetDepthWrite(const char* name, bool value) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->depthWrite = value;
}

void CMirvImageDrawer::SetAttachment(const char* name, int slot, bool useYaw, bool usePitch, bool useRoll, const char* attachmentName) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) return;
	entry->attachSlot = slot;
	entry->attachUseYaw = useYaw;
	entry->attachUsePitch = usePitch;
	entry->attachUseRoll = useRoll;
	entry->attachAttachmentName = attachmentName ? attachmentName : "";
	entry->attachValid = false;
	entry->attachSampleSerial = 0;
	entry->attachSampleValid = false;
}

void CMirvImageDrawer::UpdateAttachments() {
	UpdateAttachmentsForSetupSerial(0);
}

void CMirvImageDrawer::UpdateAttachmentsForSetupSerial(uint64_t setupSerial) {
	std::lock_guard<std::mutex> lock(m_Mutex);
	for (auto& entry : m_Images) {
		if (entry.attachSlot < 0) {
			if (0 == setupSerial) {
				entry.attachValid = false;
			} else {
				entry.attachSampleSerial = setupSerial;
				entry.attachSampleValid = false;
			}
			continue;
		}

		float eye[3] = {};
		float ang[3] = {};
		if (TryGetAttachedTransform(entry.attachSlot, entry.attachAttachmentName, eye, ang)) {
			if (0 == setupSerial) {
				entry.attachOrigin = Vector3(eye[0], eye[1], eye[2]);
				entry.attachPitch = ang[0];
				entry.attachYaw = ang[1];
				entry.attachRoll = ang[2];
				entry.attachValid = true;
			} else {
				entry.attachSampleSerial = setupSerial;
				entry.attachSampleOrigin = Vector3(eye[0], eye[1], eye[2]);
				entry.attachSamplePitch = ang[0];
				entry.attachSampleYaw = ang[1];
				entry.attachSampleRoll = ang[2];
				entry.attachSampleValid = true;
			}
		} else {
			if (0 == setupSerial) {
				entry.attachValid = false;
			} else {
				entry.attachSampleSerial = setupSerial;
				entry.attachSampleValid = false;
			}
		}
	}
}

void CMirvImageDrawer::PublishAttachmentsForSetupSerial(uint64_t setupSerial) {
	if (0 == setupSerial) return;

	std::lock_guard<std::mutex> lock(m_Mutex);
	for (auto& entry : m_Images) {
		if (entry.attachSlot < 0) {
			entry.attachValid = false;
			continue;
		}
		if (entry.attachSampleSerial != setupSerial) continue;

		entry.attachValid = entry.attachSampleValid;
		if (entry.attachSampleValid) {
			entry.attachOrigin = entry.attachSampleOrigin;
			entry.attachPitch = entry.attachSamplePitch;
			entry.attachYaw = entry.attachSampleYaw;
			entry.attachRoll = entry.attachSampleRoll;
		}
	}
}

void CMirvImageDrawer::GetAtlasSnapshot(std::vector<AtlasSnapshot>& out) {
	out.clear();
	std::lock_guard<std::mutex> lock(m_Mutex);
	out.reserve(m_Atlases.size());
	for (auto& atlas : m_Atlases) {
		AtlasSnapshot snap;
		snap.name = atlas.name;
		snap.handle = atlas.texture.handle;
		snap.width = atlas.width;
		snap.height = atlas.height;
		snap.format = atlas.format;
		snap.alphaMode = atlas.alphaMode;
		snap.keyedMutex = atlas.keyedMutex;
		snap.open = atlas.texture.srv != nullptr;
		snap.keyed = atlas.texture.keyedMutexObj != nullptr;
		snap.regions.reserve(atlas.regions.size());
		for (const auto& region : atlas.regions) {
			AtlasRegionSnapshot r;
			r.id = region.id;
			r.u0 = region.u0;
			r.v0 = region.v0;
			r.u1 = region.u1;
			r.v1 = region.v1;
			r.defaultW = region.defaultW;
			r.defaultH = region.defaultH;
			snap.regions.push_back(std::move(r));
		}
		out.push_back(std::move(snap));
	}
}

void CMirvImageDrawer::GetImageSnapshot(std::vector<ImageSnapshot>& out) {
	out.clear();
	std::lock_guard<std::mutex> lock(m_Mutex);
	out.reserve(m_Images.size());
	for (const auto& entry : m_Images) {
		ImageSnapshot snap;
		snap.name = entry.name;
		snap.position = entry.position;
		snap.pitch = entry.pitch;
		snap.yaw = entry.yaw;
		snap.roll = entry.roll;
		snap.scaleX = entry.scaleX;
		snap.scaleY = entry.scaleY;
		snap.visible = entry.visible;
		snap.depthTest = entry.depthTest;
		snap.depthWrite = entry.depthWrite;
		snap.useAtlas = entry.useAtlas;
		snap.atlasName = entry.atlasName;
		snap.regionId = entry.regionId;
		snap.attachSlot = entry.attachSlot;
		snap.attachAttachmentName = entry.attachAttachmentName;
		snap.attachUseYaw = entry.attachUseYaw;
		snap.attachUsePitch = entry.attachUsePitch;
		snap.attachUseRoll = entry.attachUseRoll;
		out.push_back(std::move(snap));
	}
}

void CMirvImageDrawer::RegisterAtlas(const char* name, const char* handleStr, UINT width, UINT height, const char* formatStr, const char* alphaStr, bool keyedMutex) {
	if (!name || !handleStr) return;
	std::lock_guard<std::mutex> lock(m_Mutex);

	AtlasEntry* atlas = FindAtlasLocked(name);
	if (!atlas) {
		AtlasEntry newEntry;
		newEntry.name = name;
		m_Atlases.push_back(std::move(newEntry));
		atlas = &m_Atlases.back();
	}

	ReleaseAtlasResources(*atlas);

	atlas->width = width;
	atlas->height = height;
	atlas->keyedMutex = keyedMutex;

	if (formatStr && 0 == _stricmp(formatStr, "RGBA8")) atlas->format = AtlasFormat::RGBA8;
	else atlas->format = AtlasFormat::BGRA8;

	if (alphaStr && 0 == _stricmp(alphaStr, "straight")) atlas->alphaMode = AlphaMode::Straight;
	else atlas->alphaMode = AlphaMode::Premultiplied;

	atlas->texture = {};
	atlas->texture.handle = (HANDLE)_strtoui64(handleStr, nullptr, 10);
}

void CMirvImageDrawer::UnregisterAtlas(const char* name) {
	if (!name) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	auto it = std::find_if(m_Atlases.begin(), m_Atlases.end(),
		[name](const AtlasEntry& entry) { return entry.name == name; });
	if (it == m_Atlases.end()) return;
	ReleaseAtlasResources(*it);
	m_Atlases.erase(it);
}

void CMirvImageDrawer::ListAtlases() {
	std::lock_guard<std::mutex> lock(m_Mutex);
	advancedfx::Message("mirv_image: %zu atlas/atlases\n", m_Atlases.size());
	for (auto& atlas : m_Atlases) {
		if (m_Device) {
			TryOpenSharedTexture(atlas);
		}
		advancedfx::Message(
			"  %s handle=%p size=%ux%u format=%s alpha=%s regions=%zu open=%d keyed=%d\n",
			atlas.name.c_str(),
			atlas.texture.handle,
			atlas.width,
			atlas.height,
			atlas.format == AtlasFormat::RGBA8 ? "RGBA8" : "BGRA8",
			atlas.alphaMode == AlphaMode::Straight ? "straight" : "premultiplied",
			atlas.regions.size(),
			atlas.texture.srv ? 1 : 0,
			atlas.texture.keyedMutexObj ? 1 : 0
		);
	}
}

void CMirvImageDrawer::SetAtlasRegion(const char* atlasName, const char* regionId, float u0, float v0, float u1, float v1, double defaultW, double defaultH) {
	if (!atlasName || !regionId) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	AtlasEntry* atlas = FindAtlasLocked(atlasName);
	if (!atlas) return;

	AtlasRegion* region = FindAtlasRegionLocked(*atlas, regionId);
	if (!region) {
		AtlasRegion newRegion;
		newRegion.id = regionId;
		atlas->regions.push_back(std::move(newRegion));
		region = &atlas->regions.back();
	}

	region->u0 = u0;
	region->v0 = v0;
	region->u1 = u1;
	region->v1 = v1;
	region->defaultW = defaultW;
	region->defaultH = defaultH;
}

void CMirvImageDrawer::RemoveAtlasRegion(const char* atlasName, const char* regionId) {
	if (!atlasName || !regionId) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	AtlasEntry* atlas = FindAtlasLocked(atlasName);
	if (!atlas) return;
	auto it = std::find_if(atlas->regions.begin(), atlas->regions.end(),
		[regionId](const AtlasRegion& region) { return region.id == regionId; });
	if (it == atlas->regions.end()) return;
	atlas->regions.erase(it);
}

void CMirvImageDrawer::UseAtlasRegion(const char* name, const char* atlasName, const char* regionId) {
	if (!name || !atlasName || !regionId) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	ImageEntry* entry = FindImageLocked(name);
	if (!entry) {
		ImageEntry newEntry;
		newEntry.name = name;
		m_Images.push_back(std::move(newEntry));
		entry = &m_Images.back();
	}

	entry->atlasName = atlasName;
	entry->regionId = regionId;
	entry->useAtlas = true;
	entry->visible = true;
	entry->pendingLoad = false;
	entry->scaleX = 0.0;
	entry->scaleY = 0.0;
	ReleaseImageResources(*entry);
}

void CMirvImageDrawer::ProbeAtlas(const char* atlasName, int x, int y) {
	if (!atlasName) return;
	std::lock_guard<std::mutex> lock(m_Mutex);
	m_ProbePending = true;
	m_ProbeAtlasName = atlasName;
	m_ProbeX = x;
	m_ProbeY = y;
}

CMirvImageDrawer::ImageEntry* CMirvImageDrawer::FindImageLocked(const std::string& name) {
	auto it = std::find_if(m_Images.begin(), m_Images.end(),
		[&name](const ImageEntry& entry) { return entry.name == name; });
	if (it == m_Images.end()) return nullptr;
	return &(*it);
}

CMirvImageDrawer::AtlasEntry* CMirvImageDrawer::FindAtlasLocked(const std::string& name) {
	auto it = std::find_if(m_Atlases.begin(), m_Atlases.end(),
		[&name](const AtlasEntry& entry) { return entry.name == name; });
	if (it == m_Atlases.end()) return nullptr;
	return &(*it);
}

CMirvImageDrawer::AtlasRegion* CMirvImageDrawer::FindAtlasRegionLocked(AtlasEntry& atlas, const std::string& regionId) {
	auto it = std::find_if(atlas.regions.begin(), atlas.regions.end(),
		[&regionId](const AtlasRegion& region) { return region.id == regionId; });
	if (it == atlas.regions.end()) return nullptr;
	return &(*it);
}

void CMirvImageDrawer::ReleaseImageResources(ImageEntry& entry) {
	if (entry.srv) { entry.srv->Release(); entry.srv = nullptr; }
	if (entry.texture) { entry.texture->Release(); entry.texture = nullptr; }
	entry.width = 0;
	entry.height = 0;
}

void CMirvImageDrawer::ReleaseAtlasResources(AtlasEntry& entry) {
	if (entry.texture.keyedMutexObj) { entry.texture.keyedMutexObj->Release(); entry.texture.keyedMutexObj = nullptr; }
	if (entry.texture.srv) { entry.texture.srv->Release(); entry.texture.srv = nullptr; }
	if (entry.texture.texture) { entry.texture.texture->Release(); entry.texture.texture = nullptr; }
	entry.texture.handle = nullptr;
	entry.texture.loggedOpenFail = false;
	entry.texture.loggedMutexFail = false;
	if (entry.localSrv) { entry.localSrv->Release(); entry.localSrv = nullptr; }
	if (entry.localTexture) { entry.localTexture->Release(); entry.localTexture = nullptr; }
	entry.localFormat = DXGI_FORMAT_UNKNOWN;
	entry.localWidth = 0;
	entry.localHeight = 0;
	entry.localValid = false;
}

void CMirvImageDrawer::EnsureLocalAtlasResources(AtlasEntry& entry, const D3D11_TEXTURE2D_DESC& desc) {
	if (!m_Device) return;
	if (entry.localTexture && entry.localSrv && entry.localFormat == desc.Format
		&& entry.localWidth == desc.Width && entry.localHeight == desc.Height) {
		return;
	}

	if (entry.localSrv) { entry.localSrv->Release(); entry.localSrv = nullptr; }
	if (entry.localTexture) { entry.localTexture->Release(); entry.localTexture = nullptr; }
	entry.localFormat = DXGI_FORMAT_UNKNOWN;
	entry.localWidth = 0;
	entry.localHeight = 0;
	entry.localValid = false;

	D3D11_TEXTURE2D_DESC localDesc = {};
	localDesc.Width = desc.Width;
	localDesc.Height = desc.Height;
	localDesc.MipLevels = 1;
	localDesc.ArraySize = 1;
	localDesc.Format = desc.Format;
	localDesc.SampleDesc.Count = 1;
	localDesc.Usage = D3D11_USAGE_DEFAULT;
	localDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;

	ID3D11Texture2D* localTex = nullptr;
	HRESULT hr = m_Device->CreateTexture2D(&localDesc, nullptr, &localTex);
	if (FAILED(hr) || !localTex) {
		advancedfx::Warning("mirv_image: failed to create local atlas texture (hr=0x%08X)\n", (unsigned)hr);
		return;
	}

	D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
	srvDesc.Format = localDesc.Format;
	srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	srvDesc.Texture2D.MostDetailedMip = 0;
	srvDesc.Texture2D.MipLevels = 1;

	ID3D11ShaderResourceView* localSrv = nullptr;
	hr = m_Device->CreateShaderResourceView(localTex, &srvDesc, &localSrv);
	if (FAILED(hr) || !localSrv) {
		localTex->Release();
		advancedfx::Warning("mirv_image: failed to create local atlas SRV (hr=0x%08X)\n", (unsigned)hr);
		return;
	}

	entry.localTexture = localTex;
	entry.localSrv = localSrv;
	entry.localFormat = localDesc.Format;
	entry.localWidth = localDesc.Width;
	entry.localHeight = localDesc.Height;
}
bool CMirvImageDrawer::TryOpenSharedTexture(AtlasEntry& entry) {
	if (!m_Device) return false;
	AtlasTexture& tex = entry.texture;
	if (!tex.handle) return false;
	if (tex.texture || tex.srv) return true;

	ID3D11Resource* resource = nullptr;
	HRESULT hr = m_Device->OpenSharedResource(tex.handle, __uuidof(ID3D11Resource), (void**)&resource);
	if (FAILED(hr) || !resource) {
		if (!tex.loggedOpenFail) {
			tex.loggedOpenFail = true;
			advancedfx::Warning("mirv_image: failed to open shared texture (hr=0x%08X)\n", (unsigned)hr);
		}
		return false;
	}

	ID3D11Texture2D* texture = nullptr;
	hr = resource->QueryInterface(__uuidof(ID3D11Texture2D), (void**)&texture);
	resource->Release();
	if (FAILED(hr) || !texture) {
		if (!tex.loggedOpenFail) {
			tex.loggedOpenFail = true;
			advancedfx::Warning("mirv_image: shared resource is not a texture (hr=0x%08X)\n", (unsigned)hr);
		}
		return false;
	}

	D3D11_TEXTURE2D_DESC desc = {};
	texture->GetDesc(&desc);
	entry.width = desc.Width;
	entry.height = desc.Height;
	tex.texture = texture;
	advancedfx::Message("mirv_image: opened shared texture %ux%u format=%u\n", desc.Width, desc.Height, (unsigned)desc.Format);

	D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
	srvDesc.Format = desc.Format;
	srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	srvDesc.Texture2D.MostDetailedMip = 0;
	srvDesc.Texture2D.MipLevels = 1;

	ID3D11ShaderResourceView* srv = nullptr;
	hr = m_Device->CreateShaderResourceView(texture, &srvDesc, &srv);
	if (FAILED(hr)) {
		ReleaseAtlasResources(entry);
		if (!tex.loggedOpenFail) {
			tex.loggedOpenFail = true;
			advancedfx::Warning("mirv_image: failed to create SRV for shared texture (hr=0x%08X)\n", (unsigned)hr);
		}
		return false;
	}
	tex.srv = srv;

	if (entry.keyedMutex) {
		IDXGIKeyedMutex* mutexObj = nullptr;
		if (SUCCEEDED(texture->QueryInterface(__uuidof(IDXGIKeyedMutex), (void**)&mutexObj))) {
			tex.keyedMutexObj = mutexObj;
		} else if (!tex.loggedMutexFail) {
			tex.loggedMutexFail = true;
			advancedfx::Warning("mirv_image: shared texture has no keyed mutex.\n");
		}
	}

	return true;
}

bool CMirvImageDrawer::AcquireAtlas(AtlasEntry& entry, DWORD key) {
	AtlasTexture& tex = entry.texture;
	if (!tex.keyedMutexObj) return true;
	auto hr = tex.keyedMutexObj->AcquireSync(key, 0);
	if (FAILED(hr) && !tex.loggedMutexFail) {
		tex.loggedMutexFail = true;
		advancedfx::Warning("mirv_image: failed to acquire keyed mutex (hr=0x%08X)\n", (unsigned)hr);
	}
	return SUCCEEDED(hr);
}

void CMirvImageDrawer::ReleaseAtlas(AtlasEntry& entry, DWORD key) {
	AtlasTexture& tex = entry.texture;
	if (!tex.keyedMutexObj) return;
	tex.keyedMutexObj->ReleaseSync(key);
}

void CMirvImageDrawer::HandlePendingProbe() {
	std::string atlasName;
	int x = 0;
	int y = 0;
	std::lock_guard<std::mutex> lock(m_Mutex);
	if (!m_ProbePending) return;
	m_ProbePending = false;
	atlasName = m_ProbeAtlasName;
	x = m_ProbeX;
	y = m_ProbeY;

	if (!m_Device || !m_ImmediateContext) return;

	AtlasEntry* atlas = FindAtlasLocked(atlasName);
	if (!atlas) {
		advancedfx::Warning("mirv_image: atlas not found.\n");
		return;
	}
	if (!TryOpenSharedTexture(*atlas)) {
		advancedfx::Warning("mirv_image: atlas texture not available.\n");
		return;
	}
	if (atlas->width == 0 || atlas->height == 0) {
		advancedfx::Warning("mirv_image: atlas has invalid size.\n");
		return;
	}

	x = (std::max)(0, (std::min)(x, (int)atlas->width - 1));
	y = (std::max)(0, (std::min)(y, (int)atlas->height - 1));

	if (!AcquireAtlas(*atlas, 1)) {
		advancedfx::Warning("mirv_image: failed to acquire keyed mutex.\n");
		return;
	}

	D3D11_TEXTURE2D_DESC desc = {};
	atlas->texture.texture->GetDesc(&desc);
	desc.BindFlags = 0;
	desc.Usage = D3D11_USAGE_STAGING;
	desc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
	desc.MiscFlags = 0;
	desc.SampleDesc.Count = 1;
	desc.SampleDesc.Quality = 0;

	ID3D11Texture2D* staging = nullptr;
	HRESULT hr = m_Device->CreateTexture2D(&desc, nullptr, &staging);
	if (FAILED(hr) || !staging) {
		ReleaseAtlas(*atlas, 0);
		advancedfx::Warning("mirv_image: failed to create staging texture (hr=0x%08X)\n", (unsigned)hr);
		return;
	}

	D3D11_BOX box = {};
	box.left = x;
	box.right = x + 1;
	box.top = y;
	box.bottom = y + 1;
	box.front = 0;
	box.back = 1;
	m_ImmediateContext->CopySubresourceRegion(staging, 0, 0, 0, 0, atlas->texture.texture, 0, &box);

	D3D11_MAPPED_SUBRESOURCE mapped = {};
	hr = m_ImmediateContext->Map(staging, 0, D3D11_MAP_READ, 0, &mapped);
	if (SUCCEEDED(hr)) {
		const unsigned char* p = reinterpret_cast<const unsigned char*>(mapped.pData);
		unsigned char r = 0, g = 0, b = 0, a = 0;
		if (desc.Format == DXGI_FORMAT_B8G8R8A8_UNORM) {
			b = p[0]; g = p[1]; r = p[2]; a = p[3];
		} else if (desc.Format == DXGI_FORMAT_R8G8B8A8_UNORM) {
			r = p[0]; g = p[1]; b = p[2]; a = p[3];
		} else {
			advancedfx::Warning("mirv_image: probe format unsupported (%u)\n", (unsigned)desc.Format);
		}
		advancedfx::Message("mirv_image: atlas '%s' pixel(%d,%d) = rgba(%u %u %u %u)\n",
			atlasName.c_str(), x, y, (unsigned)r, (unsigned)g, (unsigned)b, (unsigned)a);
		m_ImmediateContext->Unmap(staging, 0);
	} else {
		advancedfx::Warning("mirv_image: failed to map staging texture (hr=0x%08X)\n", (unsigned)hr);
	}

	staging->Release();
	ReleaseAtlas(*atlas, 0);
}

bool CMirvImageDrawer::LoadTextureFromFile(
	const std::wstring& filePath,
	ID3D11Texture2D** outTexture,
	ID3D11ShaderResourceView** outSrv,
	UINT* outWidth,
	UINT* outHeight
) {
	if (!m_Device) return false;
	if (!outTexture || !outSrv) return false;

	*outTexture = nullptr;
	*outSrv = nullptr;
	if (outWidth) *outWidth = 0;
	if (outHeight) *outHeight = 0;

	CComInitScope comInit;
	if (!comInit.IsOk()) {
		advancedfx::Warning("mirv_image: COM initialization failed.\n");
		return false;
	}

	HRESULT hr = E_FAIL;
	IWICImagingFactory* factory = nullptr;
	IWICBitmapDecoder* decoder = nullptr;
	IWICBitmapFrameDecode* frame = nullptr;
	IWICFormatConverter* converter = nullptr;
	ID3D11Texture2D* texture = nullptr;
	ID3D11ShaderResourceView* srv = nullptr;
	UINT width = 0;
	UINT height = 0;
	std::vector<unsigned char> pixels;

	do {
		hr = CoCreateInstance(
			CLSID_WICImagingFactory,
			nullptr,
			CLSCTX_INPROC_SERVER,
			IID_PPV_ARGS(&factory)
		);
		if (FAILED(hr)) break;

		hr = factory->CreateDecoderFromFilename(
			filePath.c_str(),
			nullptr,
			GENERIC_READ,
			WICDecodeMetadataCacheOnLoad,
			&decoder
		);
		if (FAILED(hr)) break;

		hr = decoder->GetFrame(0, &frame);
		if (FAILED(hr)) break;

		hr = factory->CreateFormatConverter(&converter);
		if (FAILED(hr)) break;

		hr = converter->Initialize(
			frame,
			GUID_WICPixelFormat32bppBGRA,
			WICBitmapDitherTypeNone,
			nullptr,
			0.0,
			WICBitmapPaletteTypeCustom
		);
		if (FAILED(hr)) break;

		hr = converter->GetSize(&width, &height);
		if (FAILED(hr) || 0 == width || 0 == height) break;

		pixels.resize(width * height * 4);
		hr = converter->CopyPixels(nullptr, width * 4, static_cast<UINT>(pixels.size()), pixels.data());
		if (FAILED(hr)) break;

		D3D11_SUBRESOURCE_DATA subResource = {};
		subResource.pSysMem = pixels.data();
		subResource.SysMemPitch = width * 4;

		D3D11_TEXTURE2D_DESC textureDesc = {};
		textureDesc.Width = width;
		textureDesc.Height = height;
		textureDesc.MipLevels = 1;
		textureDesc.ArraySize = 1;
		textureDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
		textureDesc.SampleDesc.Count = 1;
		textureDesc.Usage = D3D11_USAGE_IMMUTABLE;
		textureDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;

		hr = m_Device->CreateTexture2D(&textureDesc, &subResource, &texture);
		if (FAILED(hr)) break;

		D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
		srvDesc.Format = textureDesc.Format;
		srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
		srvDesc.Texture2D.MostDetailedMip = 0;
		srvDesc.Texture2D.MipLevels = 1;

		hr = m_Device->CreateShaderResourceView(texture, &srvDesc, &srv);
		if (FAILED(hr)) break;

		*outTexture = texture;
		*outSrv = srv;
		if (outWidth) *outWidth = width;
		if (outHeight) *outHeight = height;
	} while (false);

	if (FAILED(hr)) {
		if (srv) { srv->Release(); srv = nullptr; }
		if (texture) { texture->Release(); texture = nullptr; }
	}

	SafeRelease(converter);
	SafeRelease(frame);
	SafeRelease(decoder);
	SafeRelease(factory);

	return SUCCEEDED(hr);
}

void CMirvImageDrawer::EnsureDeviceResources() {
	if (!m_Device || !m_DeviceContext) return;
	if (m_VertexShader && m_PixelShader && m_InputLayout && m_ConstantBuffer && m_VertexBuffer
		&& m_BlendState && m_BlendStatePremul && m_RasterizerState && m_SamplerState && m_DepthStateOn && m_DepthStateWrite && m_DepthStateOff) {
		return;
	}

	size_t size = 0;
	void* so = LoadFromAcsShaderFileInMemory(L"afx_drawtexture_vs_5_0.acs", ShaderCombo_afx_drawtexture_vs_5_0::GetCombo(), size);
	if (so) {
		m_Device->CreateVertexShader(so, size, NULL, &m_VertexShader);

		D3D11_INPUT_ELEMENT_DESC inputDesc[5] = {
			{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"COLOR", 0, DXGI_FORMAT_B8G8R8A8_UNORM, 0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD", 1, DXGI_FORMAT_R32G32B32_FLOAT, 0, 28, D3D11_INPUT_PER_VERTEX_DATA, 0},
			{"TEXCOORD", 2, DXGI_FORMAT_R32G32B32_FLOAT, 0, 40, D3D11_INPUT_PER_VERTEX_DATA, 0},
		};
		m_Device->CreateInputLayout(inputDesc, 5, so, size, &m_InputLayout);
		free(so);
	}

	so = LoadFromAcsShaderFileInMemory(L"afx_drawtexture_ps_5_0.acs", ShaderCombo_afx_drawtexture_ps_5_0::GetCombo(), size);
	if (so) {
		m_Device->CreatePixelShader(so, size, NULL, &m_PixelShader);
		free(so);
	}

	{
		D3D11_BUFFER_DESC cbDesc = {};
		cbDesc.ByteWidth = sizeof(VS_CONSTANT_BUFFER);
		cbDesc.Usage = D3D11_USAGE_DYNAMIC;
		cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
		cbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
		m_Device->CreateBuffer(&cbDesc, nullptr, &m_ConstantBuffer);
	}

	{
		D3D11_BUFFER_DESC vbDesc = {};
		vbDesc.ByteWidth = sizeof(Vertex) * 4;
		vbDesc.Usage = D3D11_USAGE_DYNAMIC;
		vbDesc.BindFlags = D3D11_BIND_VERTEX_BUFFER;
		vbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
		m_Device->CreateBuffer(&vbDesc, nullptr, &m_VertexBuffer);
	}

	{
		D3D11_DEPTH_STENCIL_DESC depthDesc = {};
		depthDesc.DepthEnable = TRUE;
		depthDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
		depthDesc.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
		m_Device->CreateDepthStencilState(&depthDesc, &m_DepthStateOn);
	}
	{
		D3D11_DEPTH_STENCIL_DESC depthDesc = {};
		depthDesc.DepthEnable = TRUE;
		depthDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
		depthDesc.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
		m_Device->CreateDepthStencilState(&depthDesc, &m_DepthStateWrite);
	}
	{
		D3D11_DEPTH_STENCIL_DESC depthDesc = {};
		depthDesc.DepthEnable = FALSE;
		depthDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
		depthDesc.DepthFunc = D3D11_COMPARISON_ALWAYS;
		m_Device->CreateDepthStencilState(&depthDesc, &m_DepthStateOff);
	}
	{
		D3D11_SAMPLER_DESC samplerDesc = {};
		samplerDesc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
		samplerDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
		samplerDesc.ComparisonFunc = D3D11_COMPARISON_ALWAYS;
		samplerDesc.MinLOD = -D3D11_FLOAT32_MAX;
		samplerDesc.MaxLOD = D3D11_FLOAT32_MAX;
		m_Device->CreateSamplerState(&samplerDesc, &m_SamplerState);
	}
	{
		D3D11_RASTERIZER_DESC rasterizerDesc = {};
		rasterizerDesc.FillMode = D3D11_FILL_SOLID;
		rasterizerDesc.CullMode = D3D11_CULL_NONE;
		rasterizerDesc.FrontCounterClockwise = TRUE;
		rasterizerDesc.DepthClipEnable = TRUE;
		rasterizerDesc.MultisampleEnable = TRUE;
		m_Device->CreateRasterizerState(&rasterizerDesc, &m_RasterizerState);
	}
	{
		D3D11_BLEND_DESC blendDesc = {};
		blendDesc.AlphaToCoverageEnable = FALSE;
		blendDesc.IndependentBlendEnable = FALSE;
		auto& rtDesc = blendDesc.RenderTarget[0];
		rtDesc.BlendEnable = TRUE;
		rtDesc.SrcBlend = D3D11_BLEND_SRC_ALPHA;
		rtDesc.DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
		rtDesc.BlendOp = D3D11_BLEND_OP_ADD;
		rtDesc.SrcBlendAlpha = D3D11_BLEND_SRC_ALPHA;
		rtDesc.DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
		rtDesc.BlendOpAlpha = D3D11_BLEND_OP_ADD;
		rtDesc.RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
		m_Device->CreateBlendState(&blendDesc, &m_BlendState);
	}
	{
		D3D11_BLEND_DESC blendDesc = {};
		blendDesc.AlphaToCoverageEnable = FALSE;
		blendDesc.IndependentBlendEnable = FALSE;
		auto& rtDesc = blendDesc.RenderTarget[0];
		rtDesc.BlendEnable = TRUE;
		rtDesc.SrcBlend = D3D11_BLEND_ONE;
		rtDesc.DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
		rtDesc.BlendOp = D3D11_BLEND_OP_ADD;
		rtDesc.SrcBlendAlpha = D3D11_BLEND_ONE;
		rtDesc.DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
		rtDesc.BlendOpAlpha = D3D11_BLEND_OP_ADD;
		rtDesc.RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
		m_Device->CreateBlendState(&blendDesc, &m_BlendStatePremul);
	}
}

bool CMirvImageDrawer::SetMatrixConstantBuffer(const SOURCESDK::VMatrix& worldToScreenMatrix) {
	if (!m_DeviceContext || !m_ConstantBuffer) return false;

	VS_CONSTANT_BUFFER constants = {};
	constants.matrix = DirectX::XMFLOAT4X4(
		(float)worldToScreenMatrix.m[0][0], (float)worldToScreenMatrix.m[0][1], (float)worldToScreenMatrix.m[0][2], (float)worldToScreenMatrix.m[0][3],
		(float)worldToScreenMatrix.m[1][0], (float)worldToScreenMatrix.m[1][1], (float)worldToScreenMatrix.m[1][2], (float)worldToScreenMatrix.m[1][3],
		(float)worldToScreenMatrix.m[2][0], (float)worldToScreenMatrix.m[2][1], (float)worldToScreenMatrix.m[2][2], (float)worldToScreenMatrix.m[2][3],
		(float)worldToScreenMatrix.m[3][0], (float)worldToScreenMatrix.m[3][1], (float)worldToScreenMatrix.m[3][2], (float)worldToScreenMatrix.m[3][3]
	);

	D3D11_MAPPED_SUBRESOURCE mapped = {};
	if (FAILED(m_DeviceContext->Map(m_ConstantBuffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) return false;
	memcpy(mapped.pData, &constants, sizeof(constants));
	m_DeviceContext->Unmap(m_ConstantBuffer, 0);
	return true;
}

void CMirvImageDrawer::DrawImages() {
	if (!(m_Device && m_DeviceContext && m_VertexShader && m_PixelShader && m_InputLayout && m_ConstantBuffer
		&& m_VertexBuffer && m_BlendState && m_RasterizerState && m_SamplerState && m_DepthStateOn
		&& m_DepthStateWrite && m_DepthStateOff && m_ImmediateContext && m_Rtv && m_pViewPort)) {
		return;
	}

	m_DeviceContext->OMSetRenderTargets(1, &m_Rtv, m_Dsv);
	m_DeviceContext->RSSetViewports(1, m_pViewPort);

	SOURCESDK::VMatrix worldToScreenMatrix;
	if (!RenderedSetup_GetPublishedWorldToScreenMatrix(worldToScreenMatrix)) {
		return;
	}

	if (!SetMatrixConstantBuffer(worldToScreenMatrix)) return;
	m_DeviceContext->VSSetConstantBuffers(0, 1, &m_ConstantBuffer);

	UINT stride = sizeof(Vertex);
	UINT offset = 0;
	m_DeviceContext->IASetVertexBuffers(0, 1, &m_VertexBuffer, &stride, &offset);
	m_DeviceContext->IASetInputLayout(m_InputLayout);
	m_DeviceContext->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);

	m_DeviceContext->VSSetShader(m_VertexShader, nullptr, 0);
	m_DeviceContext->PSSetShader(m_PixelShader, nullptr, 0);
	m_DeviceContext->PSSetSamplers(0, 1, &m_SamplerState);
	m_DeviceContext->RSSetState(m_RasterizerState);
	{
		struct RenderItem {
			ImageEntry* entry = nullptr;
			double depth = 0.0;
			size_t order = 0;
			Vector3 position;
			double pitch = 0.0;
			double yaw = 0.0;
			double roll = 0.0;
		};
		std::vector<RenderItem> renderList;

		std::lock_guard<std::mutex> lock(m_Mutex);
		renderList.reserve(m_Images.size());
		size_t order = 0;
		for (auto& entry : m_Images) {
			if (!entry.useAtlas && entry.pendingLoad && !entry.filePath.empty()) {
				ReleaseImageResources(entry);
				entry.pendingLoad = false;
				if (!LoadTextureFromFile(entry.filePath, &entry.texture, &entry.srv, &entry.width, &entry.height)) {
					advancedfx::Warning("mirv_image: failed to load image.\n");
				}
			}
			if (!entry.visible) { ++order; continue; }

			ID3D11ShaderResourceView* srv = entry.srv;
			AlphaMode alphaMode = AlphaMode::Straight;
			if (entry.useAtlas) {
				AtlasEntry* atlas = FindAtlasLocked(entry.atlasName);
				if (!atlas) { ++order; continue; }
				if (!TryOpenSharedTexture(*atlas)) { ++order; continue; }
				AtlasRegion* region = FindAtlasRegionLocked(*atlas, entry.regionId);
				if (!region) { ++order; continue; }
				AtlasTexture& tex = atlas->texture;
				if (tex.texture) {
					if (AcquireAtlas(*atlas, 1)) {
						D3D11_TEXTURE2D_DESC desc = {};
						tex.texture->GetDesc(&desc);
						EnsureLocalAtlasResources(*atlas, desc);
						if (atlas->localTexture) {
							m_ImmediateContext->CopyResource(atlas->localTexture, tex.texture);
							atlas->localValid = true;
						}
						ReleaseAtlas(*atlas, 0);
					}
				}
				entry.u0 = region->u0;
				entry.v0 = region->v0;
				entry.u1 = region->u1;
				entry.v1 = region->v1;
				if (entry.scaleX <= 0.0 && entry.scaleY <= 0.0) {
					entry.scaleX = region->defaultW;
					entry.scaleY = region->defaultH;
				}
				srv = atlas->localSrv;
				alphaMode = atlas->alphaMode;
			} else {
				if (!entry.srv) { ++order; continue; }
			}
			if (!srv) { ++order; continue; }

			Vector3 renderPos = entry.position;
			double renderPitch = entry.pitch;
			double renderYaw = entry.yaw;
			double renderRoll = entry.roll;

			if (entry.attachSlot >= 0) {
				if (entry.attachValid) {
					double forward[3] = {};
					double right[3] = {};
					double up[3] = {};
					Afx::Math::MakeVectors(entry.attachRoll, entry.attachPitch, entry.attachYaw, forward, right, up);

					Vector3 vForward(forward[0], forward[1], forward[2]);
					Vector3 vRight(right[0], right[1], right[2]);
					Vector3 vUp(up[0], up[1], up[2]);

					renderPos = entry.attachOrigin
						+ vForward * entry.position.X
						+ vRight * entry.position.Y
						+ vUp * entry.position.Z;

					Afx::Math::QEulerAngles baseAngles(0.0, 0.0, 0.0);
					if (entry.attachUsePitch) baseAngles.Pitch = -entry.attachPitch;
					if (entry.attachUseYaw) baseAngles.Yaw = entry.attachYaw + 180.0;
					if (entry.attachUseRoll) baseAngles.Roll = -entry.attachRoll;

					Afx::Math::QEulerAngles offsetAngles(entry.pitch, entry.yaw, entry.roll);
					Afx::Math::Quaternion baseQuat = Afx::Math::Quaternion::FromQREulerAngles(
						Afx::Math::QREulerAngles::FromQEulerAngles(baseAngles)
					).Normalized();
					Afx::Math::Quaternion offsetQuat = Afx::Math::Quaternion::FromQREulerAngles(
						Afx::Math::QREulerAngles::FromQEulerAngles(offsetAngles)
					).Normalized();
					Afx::Math::Quaternion finalQuat = (baseQuat * offsetQuat).Normalized();
					Afx::Math::QEulerAngles finalAngles = finalQuat.ToQREulerAngles().ToQEulerAngles();

					renderPitch = finalAngles.Pitch;
					renderYaw = finalAngles.Yaw;
					renderRoll = finalAngles.Roll;
				} else {
					++order;
					continue;
				}
			}

			double clipZ = worldToScreenMatrix.m[2][0] * renderPos.X
				+ worldToScreenMatrix.m[2][1] * renderPos.Y
				+ worldToScreenMatrix.m[2][2] * renderPos.Z
				+ worldToScreenMatrix.m[2][3];
			double clipW = worldToScreenMatrix.m[3][0] * renderPos.X
				+ worldToScreenMatrix.m[3][1] * renderPos.Y
				+ worldToScreenMatrix.m[3][2] * renderPos.Z
				+ worldToScreenMatrix.m[3][3];
			double depth = clipW != 0.0 ? clipZ / clipW : clipZ;

			renderList.push_back({ &entry, depth, order, renderPos, renderPitch, renderYaw, renderRoll });
			++order;
		}

		std::stable_sort(renderList.begin(), renderList.end(),
			[](const RenderItem& a, const RenderItem& b) {
				if (a.entry->depthTest != b.entry->depthTest) {
					return a.entry->depthTest > b.entry->depthTest;
				}
				if (a.entry->depthWrite != b.entry->depthWrite) {
					return a.entry->depthWrite > b.entry->depthWrite;
				}
				if (!a.entry->depthWrite) {
					return a.depth > b.depth;
				}
				return a.order < b.order;
			}
		);

		for (const auto& item : renderList) {
			ImageEntry& entry = *item.entry;

			ID3D11ShaderResourceView* srv = entry.srv;
			AlphaMode alphaMode = AlphaMode::Straight;
			if (entry.useAtlas) {
				AtlasEntry* atlas = FindAtlasLocked(entry.atlasName);
				if (!atlas) continue;
				if (!TryOpenSharedTexture(*atlas)) continue;
				srv = atlas->localSrv;
				alphaMode = atlas->alphaMode;
			}
			if (!srv) continue;

		double forward[3] = {};
		double right[3] = {};
		double up[3] = {};
		Afx::Math::MakeVectors(item.roll, item.pitch, item.yaw, forward, right, up);

		Vector3 vRight(right[0], right[1], right[2]);
		Vector3 vUp(up[0], up[1], up[2]);

		double halfX = entry.scaleX * 0.5;
		double halfY = entry.scaleY * 0.5;

		Vector3 p0 = item.position - vRight * halfX + vUp * halfY;
		Vector3 p1 = item.position - vRight * halfX - vUp * halfY;
		Vector3 p2 = item.position + vRight * halfX + vUp * halfY;
		Vector3 p3 = item.position + vRight * halfX - vUp * halfY;

		D3D11_MAPPED_SUBRESOURCE mapped = {};
		if (FAILED(m_DeviceContext->Map(m_VertexBuffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) continue;
		Vertex* v = reinterpret_cast<Vertex*>(mapped.pData);

		const DWORD white = 0xFFFFFFFF;
		v[0] = { (float)p0.X, (float)p0.Y, (float)p0.Z, white, entry.u0, entry.v0, 0.0f, 0, 0, 0, 0, 0, 0 };
		v[1] = { (float)p1.X, (float)p1.Y, (float)p1.Z, white, entry.u0, entry.v1, 0.0f, 0, 0, 0, 0, 0, 0 };
		v[2] = { (float)p2.X, (float)p2.Y, (float)p2.Z, white, entry.u1, entry.v0, 0.0f, 0, 0, 0, 0, 0, 0 };
		v[3] = { (float)p3.X, (float)p3.Y, (float)p3.Z, white, entry.u1, entry.v1, 0.0f, 0, 0, 0, 0, 0, 0 };

		m_DeviceContext->Unmap(m_VertexBuffer, 0);

		ID3D11BlendState* blendState = alphaMode == AlphaMode::Premultiplied ? m_BlendStatePremul : m_BlendState;
		m_DeviceContext->OMSetBlendState(blendState, nullptr, 0xffffffff);

		ID3D11DepthStencilState* depthState = m_DepthStateOff;
		if (entry.depthTest) {
			depthState = entry.depthWrite ? m_DepthStateWrite : m_DepthStateOn;
		}
		m_DeviceContext->OMSetDepthStencilState(depthState, 0);
		m_DeviceContext->PSSetShaderResources(0, 1, &srv);
		m_DeviceContext->Draw(4, 0);

		}
	}

	ID3D11CommandList* commandList = nullptr;
	m_DeviceContext->FinishCommandList(FALSE, &commandList);
	if (commandList) {
		m_ImmediateContext->ExecuteCommandList(commandList, TRUE);
		commandList->Release();
	}

	HandlePendingProbe();
}

CON_COMMAND(mirv_image, "3D image drawing in world space.")
{
	int argc = args->ArgC();
	const char* cmd0 = args->ArgV(0);

	if (2 <= argc) {
		const char* cmd1 = args->ArgV(1);
		if (0 == _stricmp(cmd1, "load")) {
			if (4 <= argc) {
				g_MirvImageDrawer.LoadImage(args->ArgV(2), args->ArgV(3));
				return;
			}
		} else if (0 == _stricmp(cmd1, "unload")) {
			if (3 <= argc) {
				g_MirvImageDrawer.UnloadImage(args->ArgV(2));
				return;
			}
		} else if (0 == _stricmp(cmd1, "clear")) {
			g_MirvImageDrawer.Clear();
			return;
		} else if (0 == _stricmp(cmd1, "list")) {
			g_MirvImageDrawer.ListImages();
			return;
		} else if (0 == _stricmp(cmd1, "place")) {
			if (6 <= argc) {
				g_MirvImageDrawer.SetPosition(args->ArgV(2), atof(args->ArgV(3)), atof(args->ArgV(4)), atof(args->ArgV(5)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "angles")) {
			if (6 <= argc) {
				g_MirvImageDrawer.SetAngles(args->ArgV(2), atof(args->ArgV(3)), atof(args->ArgV(4)), atof(args->ArgV(5)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "scale")) {
			if (5 <= argc) {
				g_MirvImageDrawer.SetScale(args->ArgV(2), atof(args->ArgV(3)), atof(args->ArgV(4)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "show")) {
			if (4 <= argc) {
				g_MirvImageDrawer.SetVisible(args->ArgV(2), 0 != atoi(args->ArgV(3)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "depth")) {
			if (4 <= argc) {
				g_MirvImageDrawer.SetDepthTest(args->ArgV(2), 0 != atoi(args->ArgV(3)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "depthwrite")) {
			if (4 <= argc) {
				g_MirvImageDrawer.SetDepthWrite(args->ArgV(2), 0 != atoi(args->ArgV(3)));
				return;
			}
		} else if (0 == _stricmp(cmd1, "atlas")) {
			if (3 <= argc) {
				const char* cmd2 = args->ArgV(2);
				if (0 == _stricmp(cmd2, "register")) {
					if (9 <= argc) {
						g_MirvImageDrawer.RegisterAtlas(
							args->ArgV(3), args->ArgV(4),
							static_cast<UINT>(atoi(args->ArgV(5))), static_cast<UINT>(atoi(args->ArgV(6))),
							args->ArgV(7), args->ArgV(8),
							10 <= argc ? (0 != atoi(args->ArgV(9))) : true
						);
						return;
					}
				} else if (0 == _stricmp(cmd2, "unregister")) {
					if (4 <= argc) {
						g_MirvImageDrawer.UnregisterAtlas(args->ArgV(3));
						return;
					}
				} else if (0 == _stricmp(cmd2, "list")) {
					g_MirvImageDrawer.ListAtlases();
					return;
				} else if (0 == _stricmp(cmd2, "probe")) {
					if (6 <= argc) {
						g_MirvImageDrawer.ProbeAtlas(args->ArgV(3), atoi(args->ArgV(4)), atoi(args->ArgV(5)));
						return;
					}
				} else if (0 == _stricmp(cmd2, "region")) {
					if (9 <= argc) {
						double defaultW = 1.0;
						double defaultH = 1.0;
						if (11 <= argc) {
							defaultW = atof(args->ArgV(9));
							defaultH = atof(args->ArgV(10));
						}
						g_MirvImageDrawer.SetAtlasRegion(
							args->ArgV(3), args->ArgV(4),
							(float)atof(args->ArgV(5)), (float)atof(args->ArgV(6)),
							(float)atof(args->ArgV(7)), (float)atof(args->ArgV(8)),
							defaultW, defaultH
						);
						return;
					}
				}
			}
		} else if (0 == _stricmp(cmd1, "use")) {
			if (5 <= argc) {
				g_MirvImageDrawer.UseAtlasRegion(args->ArgV(2), args->ArgV(3), args->ArgV(4));
				return;
			}
		}
	}

	advancedfx::Message(
		"mirv_image load <name> <file> - Load PNG from resources\\\\AfxHookSource2\\\\images.\n"
		"mirv_image unload <name> - Unload image.\n"
		"mirv_image clear - Remove all images and atlases.\n"
		"mirv_image list - List images.\n"
		"mirv_image place <name> <x> <y> <z> - Set world position.\n"
		"mirv_image angles <name> <pitch> <yaw> <roll> - Set world angles.\n"
		"mirv_image scale <name> <sx> <sy> - Set world size.\n"
		"mirv_image show <name> 0|1 - Show or hide image.\n"
		"mirv_image depth <name> 0|1 - Disable or enable depth testing.\n"
		"mirv_image depthwrite <name> 0|1 - Disable or enable depth writing (use 0 for proper transparency).\n"
		"mirv_image use <name> <atlas> <regionId> - Bind image to atlas region.\n"
		"mirv_image atlas register <atlas> <handle> <width> <height> <format> <alphaMode> [keyedMutex]\n"
		"mirv_image atlas unregister <atlas>\n"
		"mirv_image atlas list - List atlases.\n"
		"mirv_image atlas probe <atlas> <x> <y> - Read back one atlas pixel.\n"
		"mirv_image atlas region <atlas> <regionId> <u0> <v0> <u1> <v1> [defaultW defaultH]\n"
	);
}
