on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Dispatch to Purp1e archive
      uses: mvasigh/dispatch-action@1.1.6
      with:
        # The Github access token to use (i.e. secrets.GITHUB_TOKEN)
        token: ${{ secrets.PURPLE_ARCHIVE_TOKEN }}
        # The name of the repository to dispatch the event to
        repo: HLAE-Archieve
        # The owner of the repository to dispatch the event to
        owner: Purple-CSGO
        # The type of event to be dispatched
        event_type: hlae_update_again

    - name: Dispatch to new archive repo
      uses: mvasigh/dispatch-action@1.1.6
      with:
        # The Github access token to use (i.e. secrets.GITHUB_TOKEN)
        token: ${{ secrets.PURPLE_ARCHIVE_TOKEN }}
        # The name of the repository to dispatch the event to
        repo: HLAE-Archive
        # The owner of the repository to dispatch the event to
        owner: One-Studio
        # The type of event to be dispatched
        event_type: do_archive