name: Build Release

on:
  push:
    branches: [ main ]
  merge_group:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.6.0
    - uses: MinoruSekine/setup-scoop@main

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/build/Release

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -T "v143" -A "Win32"

    - name: Install gettext
      run: scoop install gettext

    - name: Install WiX Toolset
      run: scoop install wixtoolset

    - name: Build
      run: cmake --build . --config Release -v -- -r
